// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_BaseWidget.cpp"
#include "6YEA5652QU/moc_ColorWidget.cpp"
#include "6YEA5652QU/moc_DigitalClockWidget.cpp"
#include "6YEA5652QU/moc_MainWidget.cpp"
